Make Python output unbuffered (fixes CI output)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,7 +47,7 @@ jobs:
           python-version: "3.9.0"
 
       - name: "Install Python Dependencies"
-        run: "python -m pip install --upgrade pip && pip install semver==2.13.0"
+        run: "python -u -m pip install --upgrade pip && pip install semver==2.13.0"
 
       - name: "Start X Virtual Frame Buffer"
         if: "${{ startsWith(matrix.os, 'ubuntu-') }}"
@@ -97,10 +97,10 @@ jobs:
           python-version: "3.9.0"
 
       - name: "Install Python Dependencies"
-        run: "python -m pip install --upgrade pip && pip install semver==2.13.0"
+        run: "python -u -m pip install --upgrade pip && pip install semver==2.13.0"
 
       - name: "Patch for coc.nvim Target"
-        run: "python tools/patchForTarget.py --target coc.nvim"
+        run: "python -u tools/patchForTarget.py --target coc.nvim"
 
       - name: "Install Node.js Dependencies"
         run: "npm install"
@@ -125,13 +125,13 @@ jobs:
           python-version: "3.9.0"
 
       - name: "Install Python Dependencies"
-        run: "python -m pip install --upgrade pip && pip install jsonschema==3.2.0 xmlschema==1.6.4"
+        run: "python -u -m pip install --upgrade pip && pip install jsonschema==3.2.0 xmlschema==1.6.4"
 
       - name: "Validate changelog.xml"
-        run: "python -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/changes-1.0.0.xsd\").validate(\"changelog.xml\")'"
+        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/changes-1.0.0.xsd\").validate(\"changelog.xml\")'"
 
       - name: "Validate JSON files"
-        run: "python tools/validateJsonFiles.py"
+        run: "python -u tools/validateJsonFiles.py"
 
   analyzeCodeQl:
     name: "CI - CodeQL Job"
@@ -180,22 +180,22 @@ jobs:
           python-version: "3.9.0"
 
       - name: "Install Python Dependencies"
-        run: "python -m pip install --upgrade pip && pip install semver==2.13.0"
+        run: "python -u -m pip install --upgrade pip && pip install semver==2.13.0"
 
       - name: "Set VSCODE_LTEX_VERSION"
-        run: "echo \"VSCODE_LTEX_VERSION=$(python -c \"import json; print(json.load(open('package.json', 'r'))['version'], end='')\")\" >> $GITHUB_ENV"
+        run: "echo \"VSCODE_LTEX_VERSION=$(python -u -c \"import json; print(json.load(open('package.json', 'r'))['version'], end='')\")\" >> $GITHUB_ENV"
 
       - name: "Check VSCODE_LTEX_VERSION"
         run: "if [[ -z \"$VSCODE_LTEX_VERSION\" ]]; then echo 'Error: VSCODE_LTEX_VERSION not set!'; (exit 1); fi; echo \"VSCODE_LTEX_VERSION set to '$VSCODE_LTEX_VERSION'\""
 
       - name: "Set VSCODE_LTEX_IS_PRERELEASE"
-        run: "if [[ -z \"$VSCODE_LTEX_VERSION\" ]]; then echo 'Error: VSCODE_LTEX_VERSION not set!'; (exit 1); fi; echo \"VSCODE_LTEX_IS_PRERELEASE=$(python -c \"import semver; print('true' if semver.VersionInfo.parse('$VSCODE_LTEX_VERSION').prerelease is not None else 'false', end='')\")\" >> $GITHUB_ENV"
+        run: "if [[ -z \"$VSCODE_LTEX_VERSION\" ]]; then echo 'Error: VSCODE_LTEX_VERSION not set!'; (exit 1); fi; echo \"VSCODE_LTEX_IS_PRERELEASE=$(python -u -c \"import semver; print('true' if semver.VersionInfo.parse('$VSCODE_LTEX_VERSION').prerelease is not None else 'false', end='')\")\" >> $GITHUB_ENV"
 
       - name: "Check VSCODE_LTEX_IS_PRERELEASE"
         run: "if [[ -z \"$VSCODE_LTEX_IS_PRERELEASE\" ]]; then echo 'Error: VSCODE_LTEX_IS_PRERELEASE not set!'; (exit 1); fi; echo \"VSCODE_LTEX_IS_PRERELEASE set to '$VSCODE_LTEX_IS_PRERELEASE'\""
 
       - name: "Set VSCODE_LTEX_CHANGELOG"
-        run: "if [ \"$VSCODE_LTEX_IS_PRERELEASE\" = \"false\" ]; then echo \"VSCODE_LTEX_CHANGELOG<<EOF\" >> $GITHUB_ENV; python tools/convertChangelog.py --xml-file changelog.xml --version latest >> $GITHUB_ENV; echo \"EOF\" >> $GITHUB_ENV; else echo \"VSCODE_LTEX_CHANGELOG=This is a pre-release. Use at your own risk.\" >> $GITHUB_ENV; fi"
+        run: "if [ \"$VSCODE_LTEX_IS_PRERELEASE\" = \"false\" ]; then echo \"VSCODE_LTEX_CHANGELOG<<EOF\" >> $GITHUB_ENV; python -u tools/convertChangelog.py --xml-file changelog.xml --version latest >> $GITHUB_ENV; echo \"EOF\" >> $GITHUB_ENV; else echo \"VSCODE_LTEX_CHANGELOG=This is a pre-release. Use at your own risk.\" >> $GITHUB_ENV; fi"
 
       - name: "Build Package with vsce"
         run: "vsce package"
@@ -203,7 +203,7 @@ jobs:
       - name: "Build Offline Packages"
         env:
           LTEX_GITHUB_OAUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
-        run: "python tools/createOfflinePackages.py"
+        run: "python -u tools/createOfflinePackages.py"
 
       - name: "Create GitHub Release"
         uses: "softprops/action-gh-release@v0.1.8"
