Add CI step for deploying coc-ltex to npm

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -152,8 +152,8 @@ jobs:
       - name: "Perform CodeQL Analysis"
         uses: "github/codeql-action/analyze@v1"
 
-  deploy:
-    name: "CI - Deploy Job"
+  deployForVsCode:
+    name: "CI - Deploy for VS Code Job"
     if: "${{ startsWith(github.ref, 'refs/tags/') }}"
     needs:
       - "buildForVsCode"
@@ -224,3 +224,62 @@ jobs:
         env:
           VSCODE_LTEX_OVSX_TOKEN: "${{ secrets.VSCODE_LTEX_OVSX_TOKEN }}"
         run: "ovsx publish -p \"$VSCODE_LTEX_OVSX_TOKEN\""
+
+  deployForCocNvim:
+    name: "CI - Deploy for coc.nvim Job"
+    if: "${{ startsWith(github.ref, 'refs/tags/') }}"
+    needs:
+      - "buildForVsCode"
+      - "buildForCocNvim"
+      - "validate"
+      - "analyzeCodeQl"
+    runs-on: "ubuntu-20.04"
+
+    steps:
+      - name: "Checkout Repository"
+        uses: "actions/checkout@v2"
+
+      - name: "Set up Node.js"
+        uses: "actions/setup-node@v1"
+        with:
+          node-version: "16.11.0"
+          registry-url: "https://registry.npmjs.org"
+
+      - name: "Set up Python"
+        uses: "actions/setup-python@v2"
+        with:
+          python-version: "3.9.0"
+
+      - name: "Install Python Dependencies"
+        run: "python -u -m pip install --upgrade pip && pip install semver==2.13.0"
+
+      - name: "Patch for coc.nvim Target"
+        run: "python -u tools/patchForTarget.py --target coc.nvim"
+
+      - name: "Install Node.js Dependencies"
+        run: "npm install"
+
+      - name: "Set VSCODE_LTEX_VERSION"
+        run: "echo \"VSCODE_LTEX_VERSION=$(python -u -c \"import json; print(json.load(open('package.json', 'r'))['version'], end='')\")\" >> $GITHUB_ENV"
+
+      - name: "Check VSCODE_LTEX_VERSION"
+        run: "if [[ -z \"$VSCODE_LTEX_VERSION\" ]]; then echo 'Error: VSCODE_LTEX_VERSION not set!'; (exit 1); fi; echo \"VSCODE_LTEX_VERSION set to '$VSCODE_LTEX_VERSION'\""
+
+      - name: "Set VSCODE_LTEX_IS_PRERELEASE"
+        run: "if [[ -z \"$VSCODE_LTEX_VERSION\" ]]; then echo 'Error: VSCODE_LTEX_VERSION not set!'; (exit 1); fi; echo \"VSCODE_LTEX_IS_PRERELEASE=$(python -u -c \"import semver; print('true' if semver.VersionInfo.parse('$VSCODE_LTEX_VERSION').prerelease is not None else 'false', end='')\")\" >> $GITHUB_ENV"
+
+      - name: "Check VSCODE_LTEX_IS_PRERELEASE"
+        run: "if [[ -z \"$VSCODE_LTEX_IS_PRERELEASE\" ]]; then echo 'Error: VSCODE_LTEX_IS_PRERELEASE not set!'; (exit 1); fi; echo \"VSCODE_LTEX_IS_PRERELEASE set to '$VSCODE_LTEX_IS_PRERELEASE'\""
+
+      - name: "Compile and Package"
+        run: "npm run coc.nvim:prepublish"
+
+      - name: "Publish on npm (Dry Run)"
+        if: "${{ env.VSCODE_LTEX_IS_PRERELEASE == 'true' }}"
+        run: "npm publish --dry-run"
+
+      - name: "Publish on npm"
+        if: "${{ env.VSCODE_LTEX_IS_PRERELEASE == 'false' }}"
+        env:
+          NODE_AUTH_TOKEN: "${{ secrets.VSCODE_LTEX_NPM_TOKEN }}"
+        run: "npm publish"
